version: '2.6.1'
services:

  basa:
      image: postgres:13.0-alpine
      volumes:
      - /var/lib/postgresql/data/

  backend:
    build: D:/Dev/foodgram-project-react/backend/foodgram
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
          - basa
    env_file:
      - ./.env 

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  static_value:
  media_value:
 
