version: '2.2'

services:
  basa:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
  backend:
    build: D:/Dev/foodgram-project-react/backend/foodgram/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - basa
    env_file:
      - ./.env

  frontend:
    build: D:/Dev/foodgram-project-react/frontend/
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:


